### ISSUE TITLE
molecule has dest_ports as a list, however it is a comma seperated string

### ISSUE THREAD

**Issue by p-thurner** [blunix/role-shorewall#14]
The default molecule playbook states ports as a yaml list: https://github.com/blunix/role-shorewall/blob/master/molecule/default/playbook.yml#L48

however in the template it is a string: https://github.com/blunix/role-shorewall/blob/master/templates/etc/shorewall/rules.j2#L21
```
{{ rule.dest_ports | default('-') }}
```

**Comment by baccenfutter** [comment]
correct and new is comma-separated-list.

**Comment by baccenfutter** [comment]
Fixed.
